name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configuration de Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '3.8.1'

      # Build de l'application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Déploiement sur Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mySpringBootChatApp  # Remplace avec le nom de ton app Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Profil de publication de ton app Azure
          package: ./target/*.jar  # Chemin vers ton fichier JAR généré
